name: setup-ninja

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./
      - run: ninja --version